[pytest]
# Recolecta los tests desde las carpetas reales del proyecto
testpaths = bo web .

# Patrón de archivos: incluye los que NO empiezan con test_ (como crear_op.py)
python_files = *.py
python_classes = Test*
python_functions = test_*

# Salida legible y markers estrictos
addopts = -ra --tb=short
